[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
MyModule = '0x8c0b1e17b34aacc2fc14358a6e62e09491ed5428311acbdde700cea58e210b83'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
